# Generated by Django 5.2.12 on 2026-03-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_submission_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
