# Generated by Django 5.2.12 on 2026-03-12 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_studentprofile_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_assignments', models.IntegerField(default=0)),
                ('total_assignments', models.IntegerField(default=0)),
                ('progress_percent', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='academics.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progresses', to='academics.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
